/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postIngest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIngestRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIngestRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserRisk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIncident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIncidentGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportIncident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewIncident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCampaigns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{rule_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRuleStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detection/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetectionHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvalReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetails: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            trace_id?: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        SessionUser: {
            analyst_id: string;
            name: string;
            /** @enum {string} */
            role: "analyst" | "detection_engineer";
        };
        LoginResponse: {
            user: components["schemas"]["SessionUser"];
        };
        HealthResponse: {
            status?: string;
            config_version?: string;
            data?: {
                ts_min?: string;
                ts_max?: string;
                users?: number;
                events?: number;
                last_pipeline_run?: string;
            };
            engine?: {
                rules_loaded?: number;
                cohort_models?: number;
                mode?: string;
            };
        };
        IngestRequest: {
            source: string;
            adapter: string;
            /** @enum {string} */
            mode: "file" | "inline";
            path?: string;
            records?: {
                [key: string]: unknown;
            }[];
            options?: {
                chunk_size?: number;
                dry_run?: boolean;
            };
        };
        IngestRunSummary: {
            run_id?: string;
            status?: string;
            source?: string;
            accepted?: number;
            rejected?: number;
            duplicates_skipped?: number;
            ts_range?: string[];
            rejects_sample?: {
                row?: number;
                reason?: string;
                raw?: string;
            }[];
            links?: {
                self?: string;
            };
        };
        IngestRunListResponse: {
            items?: components["schemas"]["IngestRunSummary"][];
            next_cursor?: string | null;
            total?: number;
        };
        UserListItem: {
            user_id?: string;
            name?: string;
            role?: string;
            department?: string;
            cohort_key?: string;
            current_risk?: number;
            risk_ewma?: number;
            /** @enum {string} */
            trend?: "rising" | "falling" | "flat";
            open_incidents?: number;
            departing_in_days?: number | null;
        };
        UserListResponse: {
            items?: components["schemas"]["UserListItem"][];
            next_cursor?: string | null;
            total?: number;
        };
        UserProfile: {
            user_id?: string;
            name?: string;
            email?: string;
            org?: {
                role?: string;
                department?: string;
                team?: string;
                supervisor?: string;
                cohort_size?: number;
            };
            tenure_days?: number;
            departure_date?: string | null;
            first_seen?: string;
            last_seen?: string;
            baseline?: {
                days_available?: number;
                maturity?: number;
                working_window?: {
                    start_min?: number;
                    end_min?: number;
                };
            };
            current_risk?: number;
            risk_ewma?: number;
            incident_counts?: {
                AUTO_FLAG?: number;
                ANALYST_REVIEW?: number;
                MONITOR?: number;
            };
        };
        UserRiskSeries: {
            user_id?: string;
            window?: {
                from?: string;
                to?: string;
            };
            series?: {
                date?: string;
                risk?: number;
                confidence?: number;
                risk_ewma?: number;
                signal_count?: number;
                incident_ids?: string[];
            }[];
            peer_band?: {
                date?: string;
                p50?: number;
                p90?: number;
                p99?: number;
            }[];
            summary?: {
                peak_risk?: number;
                peak_date?: string;
                days_above_threshold?: number;
                trend?: string;
            };
        };
        TimelineEvent: {
            event_id?: string;
            ts?: string;
            /** @enum {string} */
            source?: "logon" | "device" | "file" | "http" | "email";
            action?: string;
            pc_id?: string;
            attrs?: {
                [key: string]: unknown;
            };
            signal_ids?: number[];
            risk_after?: number;
            stage?: number;
        };
        UserTimeline: {
            date?: string;
            events?: components["schemas"]["TimelineEvent"][];
            working_window?: {
                start_min?: number;
                end_min?: number;
            };
            final_risk?: number;
        };
        /** @enum {string} */
        TriageLane: "AUTO_FLAG" | "ANALYST_REVIEW" | "MONITOR" | "SUPPRESSED";
        IncidentListItem: {
            incident_id?: string;
            user_id?: string;
            user_name?: string;
            department?: string;
            window?: {
                start?: string;
                end?: string;
            };
            risk?: number;
            confidence?: number;
            triage_lane?: components["schemas"]["TriageLane"];
            /** @enum {string} */
            status?: "open" | "closed";
            headline?: string;
            killchain_stages?: number[];
            max_stage?: number;
            signal_count?: number;
            event_count?: number;
            campaign_id?: string | null;
            top_signal?: {
                rule_id?: string;
                delta?: number;
            };
            baseline_days?: number | null;
            departing_in_days?: number | null;
            campaign_incident_count?: number | null;
        };
        IncidentListResponse: {
            items?: components["schemas"]["IncidentListItem"][];
            next_cursor?: string | null;
            total?: number;
            facets?: {
                lane?: {
                    [key: string]: number;
                };
                max_stage?: {
                    [key: string]: number;
                };
            };
        };
        Signal: {
            signal_id?: number;
            rule_id?: string;
            name?: string;
            category?: string;
            stage?: number;
            strength?: number;
            weight?: number;
            contribution?: number;
            phrase?: string;
            detail?: {
                feature?: string;
                observed?: number;
                threshold?: number;
                z_self?: number;
                z_peer?: number;
            };
            evidence_event_ids?: string[];
            references?: string[];
        };
        AttributionItem: {
            signal_id?: number;
            rule_id?: string;
            risk_without?: number;
            delta?: number;
            rank?: number;
            in_minimal_set?: boolean;
        };
        IncidentDetail: {
            incident_id?: string;
            user?: {
                user_id?: string;
                name?: string;
                role?: string;
                department?: string;
                cohort_size?: number;
            };
            window?: {
                start?: string;
                end?: string;
                duration_min?: number;
            };
            score?: {
                risk?: number;
                confidence?: number;
                triage_lane?: components["schemas"]["TriageLane"];
                breakdown?: {
                    prior_logit?: number;
                    rule_points?: number;
                    ml_points?: number;
                    correlation_points?: number;
                    total_logit?: number;
                    tau?: number;
                };
                confidence_terms?: {
                    agreement?: number;
                    diversity?: number;
                    completeness?: number;
                    maturity?: number;
                    caps_applied?: string[];
                };
            };
            narrative?: {
                headline?: string;
                summary?: string;
                detail_bullets?: string[];
                template_ids?: string[];
            };
            signals?: components["schemas"]["Signal"][];
            attribution?: {
                note?: string;
                items?: components["schemas"]["AttributionItem"][];
                minimal_sufficient_set?: string[];
                alert_threshold?: number;
            };
            campaign?: {
                campaign_id?: string;
                incident_count?: number;
                first_seen?: string;
                last_seen?: string;
                stage_progression?: number[];
            } | null;
            /** @enum {string} */
            status?: "open" | "closed";
            review?: {
                verdict?: string;
                note?: string;
                analyst_id?: string;
                reviewed_at?: string;
            } | null;
            config_version?: string;
            links?: {
                graph?: string;
                export?: string;
            };
        };
        GraphNode: {
            id?: string;
            ts?: string;
            source?: string;
            action?: string;
            label?: string;
            stage?: number;
            risk_contribution?: number;
            has_signal?: boolean;
            pc_id?: string;
            user_id?: string;
        };
        GraphEdge: {
            source?: string;
            target?: string;
            gap_seconds?: number;
            gap_label?: string;
            /** @enum {string} */
            type?: "temporal" | "stage_advance" | "shared_pc" | "shared_file";
            weight?: number;
        };
        IncidentGraph: {
            incident_id?: string;
            over_dense?: boolean;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            layout_hint?: string;
            stats?: {
                node_count?: number;
                edge_count?: number;
                component_diameter?: number;
            };
        };
        EvidencePack: {
            incident?: components["schemas"]["IncidentDetail"];
            raw_events?: {
                [key: string]: unknown;
            }[];
            config_snapshot?: {
                [key: string]: unknown;
            };
            watermark?: {
                exported_by?: string;
                exported_at?: string;
            };
        };
        SuppressionProposal: {
            /** @enum {string} */
            scope?: "user_rule" | "rule";
            user_id?: string | null;
            rule_id?: string;
            expires_at?: string;
        };
        ReviewRequest: {
            /** @enum {string} */
            verdict: "confirmed_threat" | "benign" | "inconclusive";
            note?: string;
            analyst_id: string;
            time_to_triage_sec?: number;
            propose_suppression?: components["schemas"]["SuppressionProposal"] | null;
        };
        ReviewResponse: {
            review_id?: number;
            incident_id?: string;
            verdict?: string;
            reviewed_at?: string;
            incident_status?: string;
            suppression?: {
                status?: string;
            } | null;
            effects?: {
                rule_stats_updated?: string[];
                user_risk_ewma_adjusted?: boolean;
            };
        };
        CampaignStageEvent: {
            date?: string;
            stage?: number;
            incident_id?: string;
            risk?: number;
            headline?: string;
        };
        Campaign: {
            campaign_id?: string;
            user_id?: string;
            first_seen?: string;
            last_seen?: string;
            incident_count?: number;
            peak_risk?: number;
            campaign_risk?: number;
            max_stage?: number;
            stage_progression?: components["schemas"]["CampaignStageEvent"][];
            narrative?: string;
        };
        CampaignListItem: {
            campaign_id?: string;
            user_id?: string;
            user_name?: string;
            first_seen?: string;
            last_seen?: string;
            incident_count?: number;
            peak_risk?: number;
            max_stage?: number;
        };
        CampaignListResponse: {
            items?: components["schemas"]["CampaignListItem"][];
            total?: number;
        };
        RuleCatalogueItem: {
            rule_id?: string;
            name?: string;
            category?: string;
            stage?: number;
            weight?: number;
            requires_baseline?: boolean;
            description?: string;
        };
        RuleListResponse: {
            config_version?: string;
            items?: components["schemas"]["RuleCatalogueItem"][];
        };
        RuleStats: {
            rule_id?: string;
            configured_weight?: number;
            fire_count?: number;
            fire_rate_per_user_day?: number;
            reviewed?: number;
            confirmed?: number;
            benign?: number;
            inconclusive?: number;
            observed_precision?: number;
            measured_log_odds?: number;
            weight_drift?: number;
            recommendation?: string;
        };
        DetectionHealth: {
            window?: {
                from?: string;
                to?: string;
            };
            alert_volume?: {
                incidents_per_day?: number;
                per_1k_users_per_day?: number;
            };
            lane_mix?: {
                [key: string]: number;
            };
            compression?: {
                signals_per_incident_mean?: number;
                events_per_incident_mean?: number;
            };
            calibration?: {
                bins?: {
                    confidence_range?: number[];
                    n?: number;
                    observed_precision?: number;
                }[];
                ece?: number;
            };
            top_firing_rules?: {
                rule_id?: string;
                count?: number;
                observed_precision?: number;
            }[];
            warnings?: string[];
        };
        EvalReport: {
            config_version?: string;
            data_source?: string;
            generated_at?: string;
            primary_metrics?: {
                insider_recall?: number[];
                incident_precision?: number[];
                auto_flag_precision?: number[];
                pr_auc?: number[];
                median_time_to_detect_days?: number;
            };
            pr_curve?: {
                precision?: number;
                recall?: number;
            }[];
            per_scenario_recall?: {
                [key: string]: number;
            };
            time_to_detect_distribution?: number[];
        };
        AnalyzeRequest: {
            user_id: string;
            date_from: string;
            date_to: string;
            options?: {
                include_graph?: boolean;
                force_recompute?: boolean;
            };
        };
        AnalyzeResponse: {
            user_id?: string;
            window?: {
                from?: string;
                to?: string;
            };
            computed_in_ms?: number;
            from_cache?: boolean;
            peak_risk?: number;
            incidents?: string[];
            campaigns?: string[];
            daily?: {
                date?: string;
                risk?: number;
                confidence?: number;
                signal_count?: number;
            }[];
            narrative?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    postIngest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRunSummary"];
                };
            };
        };
    };
    listIngestRuns: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRunListResponse"];
                };
            };
        };
    };
    getIngestRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRunSummary"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                q?: string;
                department?: string;
                role?: string;
                min_risk?: number;
                departing_within?: number;
                sort?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getUserRisk: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
                include?: string;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRiskSeries"];
                };
            };
        };
    };
    getUserTimeline: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserTimeline"];
                };
            };
        };
    };
    listIncidents: {
        parameters: {
            query?: {
                lane?: string;
                status?: string;
                min_risk?: number;
                min_confidence?: number;
                user_id?: string;
                date_from?: string;
                date_to?: string;
                stage_max?: number;
                campaign_id?: string;
                sort?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
        };
    };
    getIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getIncidentGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentGraph"];
                };
            };
        };
    };
    exportIncident: {
        parameters: {
            query?: {
                format?: "json" | "pdf";
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePack"];
                };
            };
        };
    };
    reviewIncident: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listCampaigns: {
        parameters: {
            query?: {
                user_id?: string;
                min_stage?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignListResponse"];
                };
            };
        };
    };
    getCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleListResponse"];
                };
            };
        };
    };
    getRuleStats: {
        parameters: {
            query?: {
                date_from?: string;
                date_to?: string;
            };
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleStats"];
                };
            };
        };
    };
    getDetectionHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionHealth"];
                };
            };
        };
    };
    getEvalReport: {
        parameters: {
            query?: {
                config_version?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalReport"];
                };
            };
        };
    };
    analyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
