/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suppressions */
        get: operations["list_suppressions_api_v1_suppressions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppressions/{suppression_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Suppression */
        post: operations["activate_suppression_api_v1_suppressions__suppression_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppressions/{suppression_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Suppression */
        post: operations["revoke_suppression_api_v1_suppressions__suppression_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Risk */
        get: operations["get_user_risk_api_v1_users__user_id__risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Timeline */
        get: operations["get_user_timeline_api_v1_users__user_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident Graph */
        get: operations["get_incident_graph_api_v1_incidents__incident_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask About Incident
         * @description Grounded Q&A over one incident's already-computed evidence (ADR 0004's
         *     "optional v2 gloss" - never the authoritative record, which stays the
         *     deterministic narrative). Failures degrade to a clear 503, never a 500 -
         *     a flaky external call must not take down the incident page the rest of
         *     the demo depends on.
         */
        post: operations["ask_about_incident_api_v1_incidents__incident_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Incident */
        get: operations["export_incident_api_v1_incidents__incident_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Incident */
        post: operations["review_incident_api_v1_incidents__incident_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Incident Feedback
         * @description Analyst Feedback Loop for False-Positive Reduction (Challenge 2).
         *
         *     Distinct from POST /{incident_id}/review above: a review's verdict is a
         *     general SOC disposition and never touches behavioral baselines or
         *     correlation-edge weights. This endpoint exists specifically for "the
         *     analyst is telling the system this exact pattern is not a threat, and
         *     the system should learn from it" - it records an AnalystFeedback row,
         *     closes the incident as a false positive, and (when apply_to_similar is
         *     true) recomputes this user's Pandas-derived behavioral baseline and
         *     decays this user's learned correlation-edge weights for the incident's
         *     evidence chain (api/feedback.py::submit_feedback).
         *
         *     The authenticated account (already required at the router level) is used
         *     as the analyst identity, rather than trusting a client-supplied
         *     analyst_id like the older /review endpoint does.
         */
        post: operations["submit_incident_feedback_api_v1_incidents__incident_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaigns */
        get: operations["list_campaigns_api_v1_campaigns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign */
        get: operations["get_campaign_api_v1_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_v1_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rule Stats */
        get: operations["rule_stats_api_v1_rules__rule_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detection/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detection Health */
        get: operations["detection_health_api_v1_detection_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval Report */
        get: operations["get_eval_report_api_v1_eval_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_v1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_api_v1_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_ingest_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_ingest_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live-demo/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Actions */
        get: operations["list_actions_api_v1_live_demo_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live-demo/inject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inject */
        post: operations["inject_api_v1_live_demo_inject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live-demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_v1_live_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mitigation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_v1_mitigation_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mitigation/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Actions */
        get: operations["list_actions_api_v1_mitigation_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mitigation/actions/{mitigation_action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Action */
        get: operations["get_action_api_v1_mitigation_actions__mitigation_action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mitigation/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Action For Incident */
        get: operations["get_action_for_incident_api_v1_mitigation_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mock-remediation/isolate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Isolate */
        post: operations["isolate_api_v1_mock_remediation_isolate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/verification-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Token */
        post: operations["issue_token_api_v1_incidents__incident_id__verification_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Token
         * @description Deliberately outside get_current_account - see module docstring.
         */
        post: operations["verify_token_api_v1_verify_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountOut */
        AccountOut: {
            /** Account Id */
            account_id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
        };
        /** AlertVolume */
        AlertVolume: {
            /** Incidents Per Day */
            incidents_per_day: number;
            /** Per 1K Users Per Day */
            per_1k_users_per_day: number;
        };
        /** AnalyzeDailyPoint */
        AnalyzeDailyPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Risk */
            risk: number;
            /** Confidence */
            confidence: number;
            /** Signal Count */
            signal_count: number;
        };
        /** AnalyzeOptions */
        AnalyzeOptions: {
            /**
             * Include Graph
             * @default false
             */
            include_graph: boolean;
            /**
             * Force Recompute
             * @default false
             */
            force_recompute: boolean;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** User Id */
            user_id: string;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /**
             * @default {
             *       "include_graph": false,
             *       "force_recompute": false
             *     }
             */
            options: components["schemas"]["AnalyzeOptions"];
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** User Id */
            user_id: string;
            /** Window */
            window: {
                [key: string]: string;
            };
            /** Computed In Ms */
            computed_in_ms: number;
            /** From Cache */
            from_cache: boolean;
            /** Peak Risk */
            peak_risk: number;
            /** Incidents */
            incidents: string[];
            /** Campaigns */
            campaigns: string[];
            /** Daily */
            daily: components["schemas"]["AnalyzeDailyPoint"][];
            /** Narrative */
            narrative: string | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /**
             * Disclaimer
             * @default AI assistant - grounded only in this incident's stored evidence. Not the audited record; see the narrative above for that.
             */
            disclaimer: string;
        };
        /** AttributionItemOut */
        AttributionItemOut: {
            /** Signal Id */
            signal_id: number;
            /** Rule Id */
            rule_id: string;
            /** Risk Without */
            risk_without: number;
            /** Delta */
            delta: number;
            /** Rank */
            rank: number;
            /** In Minimal Set */
            in_minimal_set: boolean;
        };
        /** AttributionOut */
        AttributionOut: {
            /** Note */
            note: string;
            /** Items */
            items: components["schemas"]["AttributionItemOut"][];
            /** Minimal Sufficient Set */
            minimal_sufficient_set: string[];
            /** Alert Threshold */
            alert_threshold: number;
        };
        /** BaselineOut */
        BaselineOut: {
            /** Days Available */
            days_available: number;
            /** Maturity */
            maturity: number;
            /** Working Window */
            working_window: {
                [key: string]: number;
            } | null;
        };
        /** BaselineUpdateOut */
        BaselineUpdateOut: {
            /** Feature Name */
            feature_name: string;
            /** Mean Value */
            mean_value: number;
            /** Std Value */
            std_value: number;
            /** P95 Value */
            p95_value: number;
            /** Sample Count */
            sample_count: number;
        };
        /** Calibration */
        Calibration: {
            /** Bins */
            bins: components["schemas"]["CalibrationBin"][];
            /** Ece */
            ece: number;
        };
        /** CalibrationBin */
        CalibrationBin: {
            /** Confidence Range */
            confidence_range: number[];
            /** N */
            n: number;
            /** Observed Precision */
            observed_precision: number | null;
        };
        /** CampaignDetailOut */
        CampaignDetailOut: {
            /** Campaign Id */
            campaign_id: string;
            /** User Id */
            user_id: string;
            /**
             * First Seen
             * Format: date
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date
             */
            last_seen: string;
            /** Incident Count */
            incident_count: number;
            /** Peak Risk */
            peak_risk: number;
            /** Campaign Risk */
            campaign_risk: number;
            /** Max Stage */
            max_stage: number;
            /** Stage Progression */
            stage_progression: components["schemas"]["StageProgressionPoint"][];
            /** Narrative */
            narrative: string;
        };
        /** CampaignListItem */
        CampaignListItem: {
            /** Campaign Id */
            campaign_id: string;
            /** User Id */
            user_id: string;
            /**
             * First Seen
             * Format: date
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date
             */
            last_seen: string;
            /** Incident Count */
            incident_count: number;
            /** Max Stage */
            max_stage: number;
            /** Peak Risk */
            peak_risk: number;
        };
        /** CampaignListResponse */
        CampaignListResponse: {
            /** Items */
            items: components["schemas"]["CampaignListItem"][];
            /** Total */
            total: number;
        };
        /** CampaignRef */
        CampaignRef: {
            /** Campaign Id */
            campaign_id: string;
            /** Incident Count */
            incident_count: number;
            /**
             * First Seen
             * Format: date
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date
             */
            last_seen: string;
            /** Stage Progression */
            stage_progression: number[];
        };
        /** Compression */
        Compression: {
            /** Signals Per Incident Mean */
            signals_per_incident_mean: number;
            /** Events Per Incident Mean */
            events_per_incident_mean: number;
        };
        /** ConfidenceTerms */
        ConfidenceTerms: {
            /** Agreement */
            agreement: number;
            /** Diversity */
            diversity: number;
            /** Completeness */
            completeness: number;
            /** Maturity */
            maturity: number;
            /** Caps Applied */
            caps_applied: string[];
        };
        /** DetectionHealthOut */
        DetectionHealthOut: {
            /** Window */
            window: {
                [key: string]: string;
            };
            alert_volume: components["schemas"]["AlertVolume"];
            /** Lane Mix */
            lane_mix: {
                [key: string]: number;
            };
            compression: components["schemas"]["Compression"];
            calibration: components["schemas"]["Calibration"];
            /** Top Firing Rules */
            top_firing_rules: components["schemas"]["TopFiringRule"][];
            /** Warnings */
            warnings: string[];
        };
        /** EdgeUpdateOut */
        EdgeUpdateOut: {
            /** Source Event Type */
            source_event_type: string;
            /** Target Event Type */
            target_event_type: string;
            /** False Positive Count */
            false_positive_count: number;
            /** Original Weight */
            original_weight: number;
            /** Current Weight */
            current_weight: number;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Verdict
             * @constant
             */
            verdict: "false_positive";
            /**
             * Reason Code
             * @enum {string}
             */
            reason_code: "approved_business_activity" | "expected_off_hours_work" | "known_usb_workflow" | "known_host_access" | "expected_bulk_access" | "test_or_training" | "other";
            /** Comment */
            comment?: string | null;
            /**
             * Apply To Similar
             * @default true
             */
            apply_to_similar: boolean;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Incident Id */
            incident_id: string;
            /** Incident Status */
            incident_status: string;
            /** Disposition */
            disposition: string | null;
            /** Feedback Id */
            feedback_id: number;
            /** Updated Baselines */
            updated_baselines: components["schemas"]["BaselineUpdateOut"][];
            /** Updated Edges */
            updated_edges: components["schemas"]["EdgeUpdateOut"][];
            score_impact: components["schemas"]["ScoreImpactOut"];
            /**
             * Processed At
             * Format: date-time
             */
            processed_at: string;
        };
        /** GraphEdgeOut */
        GraphEdgeOut: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Gap Seconds */
            gap_seconds: number;
            /** Gap Label */
            gap_label: string;
            /** Type */
            type: string;
            /** Weight */
            weight: number;
        };
        /** GraphNodeOut */
        GraphNodeOut: {
            /** Id */
            id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Source */
            source: string;
            /** Action */
            action: string;
            /** Label */
            label: string;
            /** Stage */
            stage: number | null;
            /** Risk Contribution */
            risk_contribution: number;
            /** Has Signal */
            has_signal: boolean;
            /** Pc Id */
            pc_id: string | null;
            /** User Id */
            user_id: string;
        };
        /** GraphStats */
        GraphStats: {
            /** Node Count */
            node_count: number;
            /** Edge Count */
            edge_count: number;
            /** Component Diameter */
            component_diameter: number;
        };
        /** GraphSummaryOut */
        GraphSummaryOut: {
            /** Node Count */
            node_count: number;
            /** Edge Count */
            edge_count: number;
            /** Categories */
            categories: number;
            /** Stages */
            stages: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            /** Ts Min */
            ts_min: string | null;
            /** Ts Max */
            ts_max: string | null;
            /** Users */
            users: number;
            /** Events */
            events: number;
            /** Last Pipeline Run */
            last_pipeline_run: string | null;
        };
        /** HealthEngine */
        HealthEngine: {
            /** Rules Loaded */
            rules_loaded: number;
            /** Cohort Models */
            cohort_models: number;
            /** Mode */
            mode: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Config Version */
            config_version: string;
            data: components["schemas"]["HealthData"];
            engine: components["schemas"]["HealthEngine"];
        };
        /** IncidentCounts */
        IncidentCounts: {
            /**
             * Auto Flag
             * @default 0
             */
            AUTO_FLAG: number;
            /**
             * Analyst Review
             * @default 0
             */
            ANALYST_REVIEW: number;
            /**
             * Monitor
             * @default 0
             */
            MONITOR: number;
            /**
             * Suppressed
             * @default 0
             */
            SUPPRESSED: number;
        };
        /** IncidentDetailOut */
        IncidentDetailOut: {
            /** Incident Id */
            incident_id: string;
            user: components["schemas"]["UserRef"];
            /** Window */
            window: {
                [key: string]: unknown;
            };
            score: components["schemas"]["ScoreOut"];
            narrative: components["schemas"]["NarrativeOut"];
            /** Signals */
            signals: components["schemas"]["SignalDetailOut"][];
            attribution: components["schemas"]["AttributionOut"];
            campaign: components["schemas"]["CampaignRef"] | null;
            /** Status */
            status: string;
            /** Disposition */
            disposition?: string | null;
            review: components["schemas"]["ReviewOut"] | null;
            /** Mitigations */
            mitigations: components["schemas"]["MitigationActionOut"][];
            /** Config Version */
            config_version: string;
            /** Links */
            links: {
                [key: string]: string;
            };
        };
        /** IncidentGraphOut */
        IncidentGraphOut: {
            /** Incident Id */
            incident_id: string;
            /** Over Dense */
            over_dense: boolean;
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeOut"][];
            /** Layout Hint */
            layout_hint: string;
            stats: components["schemas"]["GraphStats"];
        };
        /** IncidentListItem */
        IncidentListItem: {
            /** Incident Id */
            incident_id: string;
            /** User Id */
            user_id: string;
            /** User Name */
            user_name: string;
            /** Department */
            department: string;
            /** Window */
            window: {
                [key: string]: string;
            };
            /** Risk */
            risk: number;
            /** Confidence */
            confidence: number;
            /** Triage Lane */
            triage_lane: string;
            /** Status */
            status: string;
            /** Headline */
            headline: string;
            /** Killchain Stages */
            killchain_stages: number[];
            /** Max Stage */
            max_stage: number;
            /** Signal Count */
            signal_count: number;
            /** Event Count */
            event_count: number;
            /** Campaign Id */
            campaign_id: string | null;
            /** Top Signal */
            top_signal: {
                [key: string]: unknown;
            } | null;
        };
        /** IncidentListResponse */
        IncidentListResponse: {
            /** Items */
            items: components["schemas"]["IncidentListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
            /** Facets */
            facets: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** IngestOptions */
        IngestOptions: {
            /**
             * Chunk Size
             * @default 250000
             */
            chunk_size: number;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Source */
            source: string;
            /**
             * Adapter
             * @default cert_r42
             */
            adapter: string;
            /** Mode */
            mode: string;
            /** Path */
            path?: string | null;
            /** Records */
            records?: {
                [key: string]: unknown;
            }[] | null;
            options?: components["schemas"]["IngestOptions"];
        };
        /** IngestRunOut */
        IngestRunOut: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Source */
            source: string;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Duplicates Skipped */
            duplicates_skipped: number;
            /** Ts Range */
            ts_range: (string | null)[];
            /** Rejects Sample */
            rejects_sample: components["schemas"]["RejectSample"][];
            /** Links */
            links: {
                [key: string]: string;
            };
        };
        /** IngestRunSummary */
        IngestRunSummary: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Rows Accepted */
            rows_accepted: number;
            /** Rows Rejected */
            rows_rejected: number;
            /** Adapter Id */
            adapter_id: string | null;
        };
        /** IssueTokenResponse */
        IssueTokenResponse: {
            /** Incident Id */
            incident_id: string;
            /** Token */
            token: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Note
             * @default Single-use. This token can verify the report exactly once.
             */
            note: string;
        };
        /** LiveDemoIncidentOut */
        LiveDemoIncidentOut: {
            /** Incident Id */
            incident_id: string;
            /** Risk */
            risk: number;
            /** Confidence */
            confidence: number;
            /** Triage Lane */
            triage_lane: string;
            /** Signal Count */
            signal_count: number;
            /** Event Count */
            event_count: number;
            /** Categories */
            categories: string[];
            /** Stages */
            stages: number[];
            /** Mitigation */
            mitigation?: {
                [key: string]: unknown;
            } | null;
        };
        /** LiveDemoInjectRequest */
        LiveDemoInjectRequest: {
            /** Actions */
            actions?: string[] | null;
            /**
             * Scenario
             * @default false
             */
            scenario: boolean;
        };
        /** LiveDemoInjectResponse */
        LiveDemoInjectResponse: {
            /** User Id */
            user_id: string;
            /** Injected Through */
            injected_through: string;
            /** Incidents Today */
            incidents_today: components["schemas"]["LiveDemoIncidentOut"][];
            /** Total Incidents For User */
            total_incidents_for_user: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            account: components["schemas"]["AccountOut"];
        };
        /** MitigationActionOut */
        MitigationActionOut: {
            /** Mitigation Action Id */
            mitigation_action_id: number;
            /** Incident Id */
            incident_id: string;
            /** User Id */
            user_id: string;
            /** Flagged Ip */
            flagged_ip: string | null;
            /** Threat Weight */
            threat_weight: number;
            /** Threshold */
            threshold: number;
            /** Action Type */
            action_type: string;
            /** Target Type */
            target_type: string;
            /** Target Value */
            target_value: string | null;
            /** Status */
            status: string;
            /** Webhook Url */
            webhook_url: string;
            /** Webhook Status Code */
            webhook_status_code: number | null;
            /** Webhook Response */
            webhook_response: string | null;
            /** Isolation Status */
            isolation_status: string;
            /** Reason */
            reason: string;
            /** Error Message */
            error_message: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * MitigationStatusOut
         * @description GET /mitigation/status - a safe, non-secret probe of the pipeline's
         *     current configuration, for the dashboard and for demo verification.
         */
        MitigationStatusOut: {
            /** Enabled */
            enabled: boolean;
            /** Threshold */
            threshold: number;
            /** Webhook Url */
            webhook_url: string;
            /** Webhook Timeout Seconds */
            webhook_timeout_seconds: number;
        };
        /** NarrativeOut */
        NarrativeOut: {
            /** Headline */
            headline: string;
            /** Summary */
            summary: string;
            /** Detail Bullets */
            detail_bullets: string[];
            /** Template Ids */
            template_ids: string[];
        };
        /** PeerBandPoint */
        PeerBandPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
            /** P99 */
            p99: number;
        };
        /** ProposeSuppression */
        ProposeSuppression: {
            /** Scope */
            scope: string;
            /** User Id */
            user_id?: string | null;
            /** Cohort Key */
            cohort_key?: string | null;
            /** Rule Id */
            rule_id?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** RejectSample */
        RejectSample: {
            /** Row */
            row: number;
            /** Reason */
            reason: string;
            /** Raw */
            raw: string;
        };
        /**
         * RemediationPayload
         * @description The structured JSON body sent to the (mock) remediation webhook, and
         *     stored verbatim in `MitigationAction.payload` for auditability.
         */
        RemediationPayload: {
            /** Incident Id */
            incident_id: string;
            /** Threat Weight */
            threat_weight: number;
            /** Threshold */
            threshold: number;
            /** User Id */
            user_id: string;
            /** Flagged Ip */
            flagged_ip: string | null;
            /** Action */
            action: string;
            /** Target Type */
            target_type: string;
            /** Target */
            target: string | null;
            graph_summary: components["schemas"]["GraphSummaryOut"];
            /** Nodes */
            nodes: {
                [key: string]: unknown;
            }[];
            /** Reason */
            reason: string;
            /** Evidence */
            evidence: string[];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ReviewEffects */
        ReviewEffects: {
            /** Rule Stats Updated */
            rule_stats_updated: string[];
            /** User Risk Ewma Adjusted */
            user_risk_ewma_adjusted: boolean;
        };
        /** ReviewOut */
        ReviewOut: {
            /** Review Id */
            review_id: number;
            /** Verdict */
            verdict: string;
            /** Note */
            note: string | null;
            /** Analyst Id */
            analyst_id: string;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Verdict */
            verdict: string;
            /** Note */
            note?: string | null;
            /** Analyst Id */
            analyst_id: string;
            /** Time To Triage Sec */
            time_to_triage_sec?: number | null;
            propose_suppression?: components["schemas"]["ProposeSuppression"] | null;
        };
        /** ReviewResponse */
        ReviewResponse: {
            /** Review Id */
            review_id: number;
            /** Incident Id */
            incident_id: string;
            /** Verdict */
            verdict: string;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /** Incident Status */
            incident_status: string;
            /** Suppression */
            suppression: {
                [key: string]: unknown;
            } | null;
            effects: components["schemas"]["ReviewEffects"];
        };
        /** RiskSeriesPoint */
        RiskSeriesPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Risk */
            risk: number;
            /** Confidence */
            confidence: number;
            /** Risk Ewma */
            risk_ewma: number | null;
            /** Signal Count */
            signal_count: number;
            /** Incident Ids */
            incident_ids: string[];
        };
        /** RiskSummary */
        RiskSummary: {
            /** Peak Risk */
            peak_risk: number;
            /** Peak Date */
            peak_date: string | null;
            /** Days Above Threshold */
            days_above_threshold: number;
            /** Trend */
            trend: string;
        };
        /** RuleOut */
        RuleOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Stage */
            stage: number;
            /** Weight */
            weight: number;
            /** Requires Baseline */
            requires_baseline: boolean;
            /** Phrase */
            phrase: string;
        };
        /** RuleStatsOut */
        RuleStatsOut: {
            /** Rule Id */
            rule_id: string;
            /** Configured Weight */
            configured_weight: number;
            /** Fire Count */
            fire_count: number;
            /** Fire Rate Per User Day */
            fire_rate_per_user_day: number;
            /** Reviewed */
            reviewed: number;
            /** Confirmed */
            confirmed: number;
            /** Benign */
            benign: number;
            /** Inconclusive */
            inconclusive: number;
            /** Observed Precision */
            observed_precision: number | null;
            /** Measured Log Odds */
            measured_log_odds: number | null;
            /** Weight Drift */
            weight_drift: number | null;
            /** Recommendation */
            recommendation: string;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /** Prior Logit */
            prior_logit: number;
            /** Rule Points */
            rule_points: number;
            /** Ml Points */
            ml_points: number;
            /** Correlation Points */
            correlation_points: number;
            /** Total Logit */
            total_logit: number;
            /** Tau */
            tau: number;
        };
        /** ScoreImpactOut */
        ScoreImpactOut: {
            /** Original Risk */
            original_risk: number;
            /** Predicted Similar Risk */
            predicted_similar_risk: number;
            /** Expected Reduction */
            expected_reduction: number;
        };
        /** ScoreOut */
        ScoreOut: {
            /** Risk */
            risk: number;
            /** Confidence */
            confidence: number;
            /** Triage Lane */
            triage_lane: string;
            breakdown: components["schemas"]["ScoreBreakdown"];
            confidence_terms: components["schemas"]["ConfidenceTerms"];
        };
        /** SignalDetailOut */
        SignalDetailOut: {
            /** Signal Id */
            signal_id: number;
            /** Rule Id */
            rule_id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Stage */
            stage: number;
            /** Strength */
            strength: number;
            /** Weight */
            weight: number;
            /** Contribution */
            contribution: number;
            /** Phrase */
            phrase: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Evidence Event Ids */
            evidence_event_ids: string[];
            /** References */
            references?: string[];
        };
        /** StageProgressionPoint */
        StageProgressionPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Stage */
            stage: number;
            /** Incident Id */
            incident_id: string;
            /** Risk */
            risk: number;
            /** Headline */
            headline: string;
        };
        /** SuppressionOut */
        SuppressionOut: {
            /** Suppression Id */
            suppression_id: number;
            /** Scope */
            scope: string;
            /** User Id */
            user_id: string | null;
            /** Cohort Key */
            cohort_key: string | null;
            /** Rule Id */
            rule_id: string | null;
            /** Reason */
            reason: string;
            /** Source Review */
            source_review: number | null;
            /** Status */
            status: string;
            /** Created By */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
        };
        /** TimelineEvent */
        TimelineEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Source */
            source: string;
            /** Action */
            action: string;
            /** Pc Id */
            pc_id: string | null;
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
            /** Signal Ids */
            signal_ids: number[];
            /** Risk After */
            risk_after: number | null;
            /** Stage */
            stage: number | null;
        };
        /** TimelineResponse */
        TimelineResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Events */
            events: components["schemas"]["TimelineEvent"][];
            /** Working Window */
            working_window: {
                [key: string]: number;
            } | null;
            /** Final Risk */
            final_risk: number | null;
        };
        /** TopFiringRule */
        TopFiringRule: {
            /** Rule Id */
            rule_id: string;
            /** Count */
            count: number;
            /** Observed Precision */
            observed_precision: number | null;
        };
        /** UserDetailResponse */
        UserDetailResponse: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Email */
            email: string | null;
            org: components["schemas"]["UserOrgOut"];
            /** Tenure Days */
            tenure_days: number;
            /** Departure Date */
            departure_date: string | null;
            /**
             * First Seen
             * Format: date
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date
             */
            last_seen: string;
            baseline: components["schemas"]["BaselineOut"];
            /** Current Risk */
            current_risk: number;
            /** Risk Ewma */
            risk_ewma: number;
            incident_counts: components["schemas"]["IncidentCounts"];
        };
        /** UserListItem */
        UserListItem: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Department */
            department: string;
            /** Cohort Key */
            cohort_key: string;
            /** Current Risk */
            current_risk: number;
            /** Risk Ewma */
            risk_ewma: number;
            /** Trend */
            trend: string;
            /** Open Incidents */
            open_incidents: number;
            /** Departing In Days */
            departing_in_days: number | null;
        };
        /** UserListResponse */
        UserListResponse: {
            /** Items */
            items: components["schemas"]["UserListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /** UserOrgOut */
        UserOrgOut: {
            /** Role */
            role: string;
            /** Department */
            department: string;
            /** Team */
            team: string | null;
            /** Supervisor */
            supervisor: string | null;
            /** Cohort Size */
            cohort_size: number;
        };
        /** UserRef */
        UserRef: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Department */
            department: string;
            /** Cohort Size */
            cohort_size: number;
        };
        /** UserRiskResponse */
        UserRiskResponse: {
            /** User Id */
            user_id: string;
            /** Window */
            window: {
                [key: string]: string;
            };
            /** Series */
            series: components["schemas"]["RiskSeriesPoint"][];
            /** Peer Band */
            peer_band: components["schemas"]["PeerBandPoint"][];
            summary: components["schemas"]["RiskSummary"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyTokenRequest */
        VerifyTokenRequest: {
            /** Token */
            token: string;
        };
        /** VerifyTokenResponse */
        VerifyTokenResponse: {
            /** Valid */
            valid: boolean;
            /** Incident Id */
            incident_id: string;
            /** Risk */
            risk: number;
            /** Confidence */
            confidence: number;
            /** Triage Lane */
            triage_lane: string;
            /** Config Version */
            config_version: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Issued By */
            issued_by: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
        };
    };
    list_suppressions_api_v1_suppressions_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuppressionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_suppression_api_v1_suppressions__suppression_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suppression_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuppressionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_suppression_api_v1_suppressions__suppression_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suppression_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuppressionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                q?: string | null;
                department?: string | null;
                role?: string | null;
                min_risk?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_risk_api_v1_users__user_id__risk_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRiskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_timeline_api_v1_users__user_id__timeline_get: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                lane?: string | null;
                status?: string | null;
                min_risk?: number | null;
                min_confidence?: number | null;
                user_id?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                stage_max?: number | null;
                campaign_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_graph_api_v1_incidents__incident_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentGraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_about_incident_api_v1_incidents__incident_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_incident_api_v1_incidents__incident_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_incident_api_v1_incidents__incident_id__review_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_incident_feedback_api_v1_incidents__incident_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campaigns_api_v1_campaigns_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                min_stage?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_api_v1_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    rule_stats_api_v1_rules__rule_id__stats_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detection_health_api_v1_detection_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionHealthOut"];
                };
            };
        };
    };
    get_eval_report_api_v1_eval_report_get: {
        parameters: {
            query?: {
                config_version?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_v1_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_api_v1_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_ingest_runs_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_ingest_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_actions_api_v1_live_demo_actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    inject_api_v1_live_demo_inject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveDemoInjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveDemoInjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_v1_live_demo_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_status_api_v1_mitigation_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MitigationStatusOut"];
                };
            };
        };
    };
    list_actions_api_v1_mitigation_actions_get: {
        parameters: {
            query?: {
                incident_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MitigationActionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_action_api_v1_mitigation_actions__mitigation_action_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mitigation_action_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MitigationActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_action_for_incident_api_v1_mitigation_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MitigationActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    isolate_api_v1_mock_remediation_isolate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemediationPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_token_api_v1_incidents__incident_id__verification_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_token_api_v1_verify_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
