"""initial schema

Revision ID: 1b81a2393e53
Revises: 
Create Date: 2026-09-25 00:01:45.931783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import api.db.types


# revision identifiers, used by Alembic.
revision: str = '1b81a2393e53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('analyst','detection_engineer')", name='ck_account_role'),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('before', api.db.types.JSONBType(), nullable=True),
    sa.Column('after', api.db.types.JSONBType(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('config_versions',
    sa.Column('config_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', api.db.types.JSONBType(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('config_version')
    )
    op.create_table('ground_truth',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('scenario', sa.SmallInteger(), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'event_date')
    )
    op.create_table('ingest_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_files', api.db.types.JSONBType(), nullable=False),
    sa.Column('rows_accepted', sa.BigInteger(), nullable=False),
    sa.Column('rows_rejected', sa.BigInteger(), nullable=False),
    sa.Column('reject_samples', api.db.types.JSONBType(), nullable=True),
    sa.Column('ts_min', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ts_max', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adapter_id', sa.String(), nullable=True),
    sa.Column('config_version', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('running','success','failed','partial')", name='ck_ingest_run_status'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('max_stage', sa.SmallInteger(), nullable=False),
    sa.Column('peak_risk', sa.Float(), nullable=False),
    sa.Column('stage_progression', api.db.types.SmallIntArrayType(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pc_id', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('attrs', api.db.types.JSONBType(), nullable=False),
    sa.Column('ingest_run_id', sa.String(), nullable=False),
    sa.CheckConstraint("source IN ('logon','device','file','http','email')", name='ck_event_source'),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_runs.run_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_table('signals',
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('killchain_stage', sa.SmallInteger(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('evidence_event_ids', api.db.types.StringArrayType(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('detail', api.db.types.JSONBType(), nullable=False),
    sa.Column('config_version', sa.String(), nullable=False),
    sa.CheckConstraint('strength BETWEEN 0 AND 1', name='ck_signal_strength'),
    sa.ForeignKeyConstraint(['config_version'], ['config_versions.config_version'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_table('user_day_features',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('cohort_key', sa.String(), nullable=False),
    sa.Column('features', api.db.types.JSONBType(), nullable=False),
    sa.Column('z_self', api.db.types.JSONBType(), nullable=False),
    sa.Column('z_peer', api.db.types.JSONBType(), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.Column('baseline_maturity', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config_version', sa.String(), nullable=False),
    sa.CheckConstraint('baseline_maturity BETWEEN 0 AND 1', name='ck_udf_maturity'),
    sa.CheckConstraint('data_completeness BETWEEN 0 AND 1', name='ck_udf_completeness'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_date')
    )
    op.create_table('user_day_scores',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('risk', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('logit', sa.Float(), nullable=False),
    sa.Column('rule_points', sa.Float(), nullable=False),
    sa.Column('ml_points', sa.Float(), nullable=False),
    sa.Column('corr_points', sa.Float(), nullable=False),
    sa.Column('anomaly_pctl', sa.Float(), nullable=True),
    sa.Column('risk_ewma', sa.Float(), nullable=True),
    sa.Column('config_version', sa.String(), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_uds_confidence'),
    sa.CheckConstraint('risk BETWEEN 0 AND 100', name='ck_uds_risk'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_date')
    )
    op.create_table('user_org',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('supervisor', sa.String(), nullable=True),
    sa.Column('cohort_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'valid_from')
    )
    op.create_table('incidents',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('triage_lane', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('killchain_stages', api.db.types.SmallIntArrayType(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('category_count', sa.Integer(), nullable=False),
    sa.Column('over_dense', sa.Boolean(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config_version', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('open','in_review','closed')", name='ck_incident_status'),
    sa.CheckConstraint("triage_lane IN ('AUTO_FLAG','ANALYST_REVIEW','MONITOR','SUPPRESSED')", name='ck_incident_lane'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('attributions',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('risk_without', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('in_minimal_set', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.signal_id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'signal_id')
    )
    op.create_table('incident_edges',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('src_event', sa.String(), nullable=False),
    sa.Column('dst_event', sa.String(), nullable=False),
    sa.Column('gap_seconds', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'src_event', 'dst_event')
    )
    op.create_table('incident_events',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('node_role', sa.String(), nullable=False),
    sa.CheckConstraint("node_role IN ('signal','context')", name='ck_incident_event_role'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'event_id')
    )
    op.create_table('narratives',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('template_ids', api.db.types.StringArrayType(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('analyst_id', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_to_triage_sec', sa.Integer(), nullable=True),
    sa.CheckConstraint("verdict IN ('confirmed_threat','benign','inconclusive')", name='ck_review_verdict'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('suppressions',
    sa.Column('suppression_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('cohort_key', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('source_review', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope IN ('user','cohort','rule','user_rule')", name='ck_suppression_scope'),
    sa.CheckConstraint("status IN ('proposed','active','revoked')", name='ck_suppression_status'),
    sa.ForeignKeyConstraint(['source_review'], ['reviews.review_id'], ),
    sa.PrimaryKeyConstraint('suppression_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppressions')
    op.drop_table('reviews')
    op.drop_table('narratives')
    op.drop_table('incident_events')
    op.drop_table('incident_edges')
    op.drop_table('attributions')
    op.drop_table('incidents')
    op.drop_table('user_org')
    op.drop_table('user_day_scores')
    op.drop_table('user_day_features')
    op.drop_table('signals')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('events')
    op.drop_table('campaigns')
    op.drop_table('users')
    op.drop_table('ingest_runs')
    op.drop_table('ground_truth')
    op.drop_table('config_versions')
    op.drop_table('audit_log')
    op.drop_table('accounts')
    # ### end Alembic commands ###
