"""add ip_address, incident pc_id/flagged_ip, mitigation_actions

Revision ID: 2844566c110f
Revises: 1b81a2393e53
Create Date: 2026-09-27 13:44:54.983881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import api.db.types


# revision identifiers, used by Alembic.
revision: str = '2844566c110f'
down_revision: Union[str, Sequence[str], None] = '1b81a2393e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitigation_actions',
    sa.Column('mitigation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('flagged_ip', sa.String(), nullable=True),
    sa.Column('threat_weight', sa.Float(), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('webhook_status', sa.String(), nullable=False),
    sa.Column('webhook_response_code', sa.Integer(), nullable=True),
    sa.Column('isolated_entity', api.db.types.JSONBType(), nullable=False),
    sa.Column('payload', api.db.types.JSONBType(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mitigation_id')
    )
    op.add_column('events', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('pc_id', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('flagged_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'flagged_ip')
    op.drop_column('incidents', 'pc_id')
    op.drop_column('events', 'ip_address')
    op.drop_table('mitigation_actions')
    # ### end Alembic commands ###
