"""restructure mitigation actions for full pipeline spec

Revision ID: a86e95be8a23
Revises: 2844566c110f
Create Date: 2026-09-27 14:48:33.961339

Hand-written, not autogenerated: the primary key column itself is renamed
(mitigation_id -> mitigation_action_id), which SQLite cannot express as a
plain ADD/DROP COLUMN sequence (autogenerate's own diff tried exactly that
and would fail - SQLite requires table recreation for a primary key change).
Since `mitigation_actions` has no rows in any environment yet (this table
was only just introduced), a drop-and-recreate loses nothing.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import api.db.types

# revision identifiers, used by Alembic.
revision: str = 'a86e95be8a23'
down_revision: Union[str, Sequence[str], None] = '2844566c110f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_table('mitigation_actions')
    op.create_table('mitigation_actions',
    sa.Column('mitigation_action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('flagged_ip', sa.String(), nullable=True),
    sa.Column('threat_weight', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('webhook_status_code', sa.Integer(), nullable=True),
    sa.Column('webhook_response', sa.String(), nullable=True),
    sa.Column('isolation_status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('payload', api.db.types.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('SUCCESS','FAILED')", name='ck_mitigation_action_status'),
    sa.CheckConstraint(
        "isolation_status IN ('SIMULATED_ISOLATED','NOT_ISOLATED')", name='ck_mitigation_action_isolation'
    ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mitigation_action_id'),
    sa.UniqueConstraint('incident_id', name='uq_mitigation_action_incident'),
    )
    op.create_index('ix_mitigation_actions_status', 'mitigation_actions', ['status'], unique=False)
    op.create_index('ix_mitigation_actions_user_id', 'mitigation_actions', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_mitigation_actions_user_id', table_name='mitigation_actions')
    op.drop_index('ix_mitigation_actions_status', table_name='mitigation_actions')
    op.drop_table('mitigation_actions')
    op.create_table('mitigation_actions',
    sa.Column('mitigation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('flagged_ip', sa.String(), nullable=True),
    sa.Column('threat_weight', sa.Float(), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('webhook_status', sa.String(), nullable=False),
    sa.Column('webhook_response_code', sa.Integer(), nullable=True),
    sa.Column('isolated_entity', api.db.types.JSONBType(), nullable=False),
    sa.Column('payload', api.db.types.JSONBType(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mitigation_id'),
    )
